# Generated by Django 4.2 on 2023-04-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=22)),
                ('lname', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=22)),
                ('phone', models.CharField(max_length=13)),
                ('id_no', models.CharField(max_length=122)),
            ],
        ),
    ]
