# Generated by Django 4.2 on 2023-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_dat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(max_length=122),
        ),
    ]
